### ISSUE TITLE
Feature idea: range :: Natural -> Natural -> Array Natural

### ISSUE THREAD

**Issue by bbarker** [LiamGoodacre/purescript-naturals#5]
A `range` function to support ranges of natural numbers (`Array Natural`) - which *should* be faster than converting an `Array Int` to `Array Natural`, as well as being more ergonomic.

**Comment by LiamGoodacre** [comment]
I'm not opposed to adding this.  However, `Natural` does implement `Enum` - is this acceptable for your use: https://pursuit.purescript.org/packages/purescript-enums/4.0.1/docs/Data.Enum#v:enumFromTo
